import React from 'react';
import { Bar } from 'react-chartjs-2';
import TokenLogo from '../Tokenpage/images/bae-token.jpg'; // Update with the correct path to your logo
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

// Register Chart.js components
ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend);

const TokenReward = () => {
  // Data for the chart
  const data = {
    labels: [
      '0 – 1m',
      '1m – 10m',
      '10m – 25m',
      '25m – 50m',
      '50m +',
    ],
    datasets: [
      {
        label: 'Revenue Percentage',
        data: [5, 10, 15, 20, 25],
        backgroundColor: 'rgba(66, 153, 225, 0.6)', // You can change this color
      },
    ],
  };

  // Chart options
  const options = {
    responsive: true,
    plugins: {
      legend: {
        position: 'top',
      },
      title: {
        display: true,
        text: 'Token Market Cap Rewards',
      },
    },
  };

  return (
    <section className="py-20 bg-gray-900 text-white">
      <div className="container mx-auto max-w-5xl px-4">
        <h2 className="text-4xl font-bold text-center mb-10">Token Holder Rewards Schedule</h2>
        
        <div className="flex items-center justify-center mb-8">
          <img src={TokenLogo} alt="$BAE Token Logo" className="h-16 w-16 mr-4" />
          <h3 className="text-2xl font-semibold">Join the Rewards Program</h3>
        </div>

        <div className="border-t border-gray-600 pt-4 mb-8">
          <h3 className="text-2xl font-semibold mb-4">+ Weekly Fee Distribution</h3>
          <p className="text-gray-300">
            We are excited to introduce an exclusive rewards program for holders of $BAE tokens! As a $BAE token holder with a minimum of 1,000,000 tokens, you are entitled to a share of the fees generated from transactions on our platform. This reward is distributed on a weekly basis, offering you a consistent return on your investment and aligning your interests with the success of the $BAE ecosystem.
          </p>
        </div>

        <div className="border-t border-gray-600 pt-4 mb-8">
          <h3 className="text-2xl font-semibold mb-4">Rewards Schedule</h3>
          <p className="text-lg font-bold text-center mb-2">**First distribution date: November 2nd, 2024**</p>
        </div>

        <div className="border-t border-gray-600 pt-4 mb-8">
          <h3 className="text-2xl font-semibold mb-4">Eligibility</h3>
          <p className="text-gray-300">
            To qualify for the weekly fee distribution, you must hold a minimum of 1,000,000 $BAE tokens in your wallet. All holders will receive the same amount, bringing equality to the project and building a much larger community that can actively be rewarded.
          </p>
        </div>

        <div className="border-t border-gray-600 pt-4 mb-8">
          <h3 className="text-2xl font-semibold mb-4">Fee Collection</h3>
          <p className="text-gray-300">
            Throughout the week, all transaction fees generated on our platform are collected via our invoicing platform. This revenue comes from the cost of BAEBOT, which is set at $20. The payment can be made in several different currencies *see below*, making BAEBOT the most versatile chain-agnostic bot in the web3 space.
          </p>
        </div>

        <div className="border-t border-gray-600 pt-4 mb-8">
          <h3 className="text-2xl font-semibold mb-4">Reward Calculation</h3>
          <p className="text-gray-300">
            The weekly reward is determined by the total fees collected during the week and the market cap of the $BAE token at the time of the snapshot. SOL will be distributed to all holders directly to their wallets holding a minimum of 1,000,000 $BAE tokens.
          </p>
        </div>

        <div className="border-t border-gray-600 pt-4 mb-8">
          <h3 className="text-2xl font-semibold mb-4">Transparency</h3>
          <p className="text-gray-300">
            All transactions and distributions are recorded on the blockchain, ensuring transparency and accountability. You can track the fee collection and reward distribution through our official channels or dashboard.
          </p>
        </div>

        <div className="border-t border-gray-600 pt-4 mb-8">
          <h3 className="text-2xl font-semibold mb-4">Benefits</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>Consistent Returns: Enjoy a regular income stream from the fees generated by the $BAE ecosystem, providing a steady return on your investment.</li>
            <li>Incentivized Holding: By holding a minimum of 1,000,000 $BAE tokens, you are rewarded for your commitment and support, reinforcing the value of long-term holding.</li>
            <li>Alignment with Success: Your rewards are directly tied to the success of the platform, aligning your interests with the growth and profitability of the $BAE ecosystem.</li>
            <li>Passive Income: Receive rewards passively without the need to actively manage or trade your tokens, making it easy to benefit from your investment.</li>
          </ul>
        </div>

        <div className="border-t border-gray-600 pt-4 mb-8">
          <h3 className="text-2xl font-semibold mb-4">Token Market Cap Rewards</h3>
          <div className="max-w-xl mx-auto">
            <Bar data={data} options={options} />
          </div>
        </div>

        <div className="text-sm font-bold text-center mt-4">
          <p>**BONUS TOP OFFS – Before the snapshot is taken – Team BaeBot will top off the top 2 wallets below 1M tokens up to 1M so they will qualify for the SOL rewards!**</p>
        </div>
      </div>
    </section>
  );
};

export default TokenReward;
